In [ ]:
import numpy as np
import random as rnd

Error

In [ ]:
import random
w = [random.randrange(0, 2)]
m = []
#for n in range(100):
for i in range(10):
    m.append(random.randrange(0, 2))
print(m)

[1, 1, 1, 1, 0, 0, 1, 1, 0, 1]


In [ ]:
filas = 100
columnas = 10

M = np.zeros((filas,columnas))

for n in range(filas):
  for i in range(columnas):
    M[n,i] = random.randrange(0,2)
print(M)

M1 = np.copy(M)

[[1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 1. 0. 1. 0. 0. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1. 1. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [1. 0. 1. 1. 1. 1. 0. 0. 1. 0.]
 [1. 1. 1. 1. 1. 0. 0. 1. 0. 1.]
 [0. 0. 0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 1. 1. 1. 0. 1. 0. 1. 1. 1.]
 [0. 0. 1. 0. 1. 1. 0. 0. 1. 1.]
 [0. 1. 1. 0. 0. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 0. 0. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0. 0. 1. 0. 1. 1.]
 [0. 1. 0. 1. 0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 0. 1. 0. 0.]
 [1. 1. 1. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 0. 1. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 1. 0. 0. 0. 1. 0. 1. 0.]
 [1. 1. 0. 1. 1. 0. 1. 0. 0. 0.]
 [0. 0. 1. 1. 0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0. 1. 0. 1. 1.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0.

In [ ]:
v = np.zeros((filas,columnas))

for n in range(filas):
  for i in range(columnas):
    v[n,i] = round(np.random.rand(),2)
print(v)


[[0.43 0.01 0.49 0.89 0.83 0.4  0.23 0.18 0.14 0.78]
 [0.61 0.68 0.81 0.93 0.84 0.57 0.65 0.68 0.38 0.83]
 [0.77 0.47 0.67 0.62 0.62 0.83 0.04 0.63 0.18 0.35]
 [0.04 0.51 0.78 0.78 0.67 0.68 0.93 0.7  0.41 0.66]
 [0.53 0.06 0.05 0.6  0.13 0.51 0.51 0.41 0.41 0.33]
 [0.87 0.91 0.5  0.14 0.24 0.05 0.   0.76 0.71 0.62]
 [0.5  0.86 0.87 0.95 0.65 0.45 0.38 0.12 0.03 0.55]
 [0.12 0.73 0.16 0.48 0.66 0.9  0.7  0.07 0.81 0.31]
 [0.65 0.12 0.59 0.49 0.89 0.83 0.15 0.31 0.66 0.52]
 [0.02 0.59 0.97 0.18 0.64 0.13 0.99 0.29 0.95 0.9 ]
 [0.29 0.99 0.19 0.31 0.58 0.71 0.73 0.04 0.17 0.65]
 [0.36 0.27 0.61 0.08 0.81 0.37 0.11 0.16 0.71 0.68]
 [0.78 0.77 0.99 0.59 0.13 0.6  0.38 0.85 0.2  0.55]
 [0.1  0.61 0.05 0.9  0.72 0.07 0.9  0.95 0.72 0.24]
 [0.04 0.65 0.39 0.18 0.23 0.94 0.79 0.01 0.62 0.09]
 [0.18 0.03 0.3  0.63 0.6  0.27 0.65 0.6  0.36 0.85]
 [0.51 0.85 0.76 0.1  0.24 0.25 0.65 0.41 0.04 1.  ]
 [0.15 0.56 0.17 0.09 0.03 0.44 0.34 0.33 0.54 0.19]
 [0.55 0.29 0.46 0.33 0.94 0.42 0.96 0.47 0.93

In [ ]:
r =np.zeros((filas,columnas))
r1 = np.zeros((filas,columnas))
for i in range(filas):
  r[i,:]=M1[i,:]+v[i,:]
  r1[i,:]=M1[i,:]+v[i,:]

In [ ]:
r

array([[1.43, 0.01, 0.49, 0.89, 0.83, 0.4 , 1.23, 0.18, 0.14, 0.78],
       [1.61, 1.68, 0.81, 1.93, 0.84, 0.57, 1.65, 1.68, 1.38, 1.83],
       [1.77, 0.47, 0.67, 1.62, 1.62, 1.83, 1.04, 0.63, 0.18, 0.35],
       [0.04, 1.51, 0.78, 0.78, 1.67, 1.68, 1.93, 1.7 , 0.41, 1.66],
       [0.53, 0.06, 0.05, 0.6 , 0.13, 0.51, 1.51, 0.41, 0.41, 0.33],
       [0.87, 0.91, 0.5 , 0.14, 1.24, 0.05, 1.  , 0.76, 0.71, 0.62],
       [1.5 , 0.86, 1.87, 1.95, 1.65, 1.45, 0.38, 0.12, 1.03, 0.55],
       [1.12, 1.73, 1.16, 1.48, 1.66, 0.9 , 0.7 , 1.07, 0.81, 1.31],
       [0.65, 0.12, 0.59, 1.49, 0.89, 0.83, 1.15, 0.31, 0.66, 1.52],
       [0.02, 1.59, 1.97, 1.18, 0.64, 1.13, 0.99, 1.29, 1.95, 1.9 ],
       [0.29, 0.99, 1.19, 0.31, 1.58, 1.71, 0.73, 0.04, 1.17, 1.65],
       [0.36, 1.27, 1.61, 0.08, 0.81, 0.37, 1.11, 0.16, 0.71, 1.68],
       [0.78, 1.77, 1.99, 0.59, 0.13, 0.6 , 0.38, 1.85, 1.2 , 0.55],
       [1.1 , 0.61, 1.05, 1.9 , 1.72, 0.07, 0.9 , 1.95, 1.72, 1.24],
       [1.04, 1.65, 1.39, 1.18, 0.

In [ ]:
r2 = np.where(r <= 0.4 , 3, r)
r4 = np.where(r2 <= 1, 4, r2)
r6 = np.where(r4 <= 1.4, 3,r4)
r8 = np.where(r6 <= 2, 4, r6)

s=np.where(r8 >= 3,0,r8)
s1=np.where(r8 >= 4, 1, s)

In [ ]:
s1

array([[1., 0., 1., 1., 1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 1., 0., 1., 1., 1., 1., 0.],
       [1., 1., 1., 0., 0., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 1.],
       [0., 1., 0., 1., 1., 1., 1., 0., 1., 0.],
       [1., 0., 1., 1., 1., 1., 0., 0., 1., 1.],
       [0., 1., 1., 0., 1., 0., 1., 0., 1., 1.],
       [0., 1., 0., 0., 1., 1., 1., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 1., 0., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 1., 1., 0., 1., 0.],
       [0., 0., 0., 1., 1., 0., 1., 1., 0., 1.],
       [1., 1., 1., 0., 0., 0., 1., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 1., 0., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 0., 

In [ ]:
f=np.zeros((100,10))

for i in range(filas):
  for j in range(columnas):
    if M1[i,j] == s1[i,j]:
      f=M1[i,j]
    else:
      f=2
print(f)

1.0


In [ ]:
r2 = np.where(r <= 0.4 , 5, r)
r4 = np.where(r2 <= 1, 3, r2)
r6 = np.where(r4 <= 1.4, 4,r4)
r8 = np.where(r6 <= 2, 5, r6)


s=np.where(r8 >= 3, 0,r8)
s1=np.where(r8 >= 4, 1, s)
s0 = np.where(r8 >= 5 ,2,s1)

In [ ]:
s0

array([[2., 2., 0., 0., 0., 2., 1., 2., 2., 0.],
       [2., 2., 0., 2., 0., 0., 2., 2., 1., 2.],
       [2., 0., 0., 2., 2., 2., 1., 0., 2., 2.],
       [2., 2., 0., 0., 2., 2., 2., 2., 0., 2.],
       [0., 2., 2., 0., 2., 0., 2., 0., 0., 2.],
       [0., 0., 0., 2., 1., 2., 0., 0., 0., 0.],
       [2., 0., 2., 2., 2., 2., 2., 2., 1., 0.],
       [1., 2., 1., 2., 2., 0., 0., 1., 0., 1.],
       [0., 2., 0., 2., 0., 0., 1., 2., 0., 2.],
       [2., 2., 2., 1., 0., 1., 0., 1., 2., 2.],
       [2., 0., 1., 2., 2., 2., 0., 2., 1., 2.],
       [2., 1., 2., 2., 0., 2., 1., 2., 0., 2.],
       [0., 2., 2., 0., 2., 0., 2., 2., 1., 0.],
       [1., 0., 1., 2., 2., 2., 0., 2., 2., 1.],
       [1., 2., 1., 1., 2., 2., 0., 1., 0., 1.],
       [1., 1., 2., 2., 0., 2., 2., 0., 1., 2.],
       [0., 2., 0., 1., 2., 2., 2., 2., 1., 0.],
       [1., 0., 1., 2., 2., 0., 2., 1., 0., 2.],
       [0., 1., 0., 1., 0., 2., 2., 2., 2., 2.],
       [2., 1., 1., 2., 0., 2., 0., 2., 0., 2.],
       [2., 2., 1., 